# Generated by Django 3.2.13 on 2022-08-23 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vagas.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do cargo')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='NOME')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[vagas.validations.validate_CNPJ], verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=60, verbose_name='Endereço p/ encaminhamento')),
                ('telefone', models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone p/ encaminhamento')),
                ('whatsapp', models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Whatsapp p/ encaminhamento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email p/ encaminhamento')),
                ('ocultar', models.BooleanField(choices=[(True, 'Ocultar informações da empresa ao encaminhar'), (False, 'Exibir informações da empresa ao encaminhar')], default=True, verbose_name='Informações da empresa')),
                ('contato_presencial', models.BooleanField(default=False, verbose_name='Contato presencial')),
                ('contato_email', models.BooleanField(default=False, verbose_name='Contato por email')),
                ('contato_telefone', models.BooleanField(default=False, verbose_name='Contato por telefone')),
                ('contato_whatsapp', models.BooleanField(default=False, verbose_name='Contato por whatsapp')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observações internas')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da escolaridade')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga_Emprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeVagas', models.IntegerField(verbose_name='Quantidade de vagas')),
                ('tipo_de_vaga', models.CharField(choices=[('NML', 'Padrão'), ('JAP', 'Jovem aprendiz'), ('PED', 'Pessoa com deficiência')], default='NML', max_length=3)),
                ('salario', models.CharField(blank=True, default='', max_length=50, verbose_name='Salário')),
                ('carga_horaria', models.CharField(blank=True, default='', max_length=50, verbose_name='Carga Hórario')),
                ('regime', models.CharField(blank=True, default='', max_length=100)),
                ('experiencia', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Experiência')),
                ('atribuicoes', models.TextField(blank=True, default='', verbose_name='Atribuições')),
                ('destaque', models.BooleanField(default=False)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('ativo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.empresa')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.escolaridade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaga de Emprego',
                'verbose_name_plural': 'Vagas de Emprego',
                'ordering': ['cargo', 'empresa'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do candidato')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento do candidato')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('o', 'Outro')], max_length=1, verbose_name='Sexo do candidato')),
                ('email', models.EmailField(max_length=254, verbose_name='Email p/ contato com o candidato')),
                ('celular', models.CharField(blank=True, max_length=11, null=True, validators=[vagas.validations.validate_TELEFONE], verbose_name='Celular p/ contato com o candidato')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro do candidato')),
                ('candidato_online', models.BooleanField(default=False, verbose_name='Candidato online')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('candidato_ativo', models.BooleanField(default=True)),
                ('conseguiu_vaga', models.BooleanField(default=False)),
                ('dt_aquisicao', models.DateTimeField(verbose_name='Dt. Aquisição Vaga')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.escolaridade')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga_emprego')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nome'],
            },
        ),
    ]
