# Generated by Django 3.1.4 on 2022-09-08 14:15

from django.db import migrations, models
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(default=0, max_length=15, validators=[vagas.validations.validate_TELEFONE], verbose_name='Celular p/ contato com o candidato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email p/ contato com o candidato'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='carga_horaria',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Carga Horária'),
        ),
    ]
