# Generated by Django 3.2.15 on 2022-10-11 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF do candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='dt_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última atualização do candidato'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='funcionario_encaminhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='vaga_emprego',
            name='dt_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt. Desativação'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(default='', max_length=15, validators=[vagas.validations.validate_TELEFONE], verbose_name='Celular p/ contato com o candidato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de inclusão do candidato'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email p/ contato com o candidato'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=254, verbose_name='Email p/ encaminhamento'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='carga_horaria',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='tipo_de_vaga',
            field=models.CharField(choices=[('NML', 'Padrão'), ('JAP', 'Jovem aprendiz'), ('PED', 'Pessoa com deficiência'), ('EST', 'Estágio')], default='NML', max_length=3),
        ),
    ]
