# Generated by Django 4.2.2 on 2023-06-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga_emprego',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='banner_vaga', verbose_name='Arte da vaga'),
        ),
    ]
