# Generated by Django 3.2.13 on 2022-08-25 17:51

from django.db import migrations, models
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_alter_candidato_dt_aquisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[vagas.validations.validate_TELEFONE], verbose_name='Celular p/ contato com o candidato'),
        ),
    ]
