# Generated by Django 3.2.12 on 2022-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_auto_20220908_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=254, verbose_name='Email p/ encaminhamento'),
        ),
    ]
