# Generated by Django 3.2.13 on 2022-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_auto_20220908_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga_emprego',
            name='tipo_de_vaga',
            field=models.CharField(choices=[('NML', 'Padrão'), ('JAP', 'Jovem aprendiz'), ('PED', 'Pessoa com deficiência'), ('EST', 'Estágio')], default='NML', max_length=3),
        ),
    ]
