# Generated by Django 3.2.12 on 2022-09-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_alter_empresa_email'),
        ('vagas', '0003_alter_vaga_emprego_tipo_de_vaga'),
    ]

    operations = [
    ]
