# Generated by Django 3.2.19 on 2023-06-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vaga_emprego_banner_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('banner_img', models.ImageField(upload_to='banner_evento', verbose_name='Arte do evento')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
