# Generated by Django 3.2.13 on 2022-09-30 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0004_merge_20220930_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(default=4, max_length=14, validators=[vagas.validations.validate_CPF], verbose_name='CPF do candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='funcionario_encaminhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaga_emprego',
            name='dt_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt. Desativação'),
        ),
    ]
