# Generated by Django 4.2.2 on 2023-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_auto_20230621_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contato_link',
            field=models.BooleanField(default=False, verbose_name='Contato por whatsapp'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link',
            field=models.CharField(blank=True, max_length=254, verbose_name='Link p/ encaminhamento'),
        ),
    ]
