# Generated by Django 3.2.13 on 2022-10-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_alter_candidato_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='dt_atualizaocao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última atualização do candidato'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='dt_inclusao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de inclusão do candidato'),
        ),
    ]
