# Generated by Django 4.2.2 on 2024-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_vaga_emprego_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga_emprego',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
    ]
