# Generated by Django 3.2.13 on 2022-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_rename_dt_atualizaocao_candidato_dt_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='dt_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última atualização do candidato'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de inclusão do candidato'),
        ),
    ]
