# Generated by Django 4.2.20 on 2025-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_alter_vaga_emprego_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga_emprego',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Email p/ encaminhamento'),
        ),
    ]
