# Generated by Django 3.2.13 on 2022-08-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0013_auto_20220620_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga_emprego',
            name='atribuicoes',
            field=models.TextField(blank=True, default='', verbose_name='Atribuições'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='carga_horaria',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Carga Hórario'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='salario',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='tipo_de_vaga',
            field=models.CharField(choices=[('NML', 'Padrão'), ('JAP', 'Jovem aprendiz'), ('PED', 'Pessoa com deficiência')], default='NML', max_length=3),
        ),
    ]
