# Generated by Django 3.2.12 on 2022-08-18 16:57

from django.db import migrations, models
import django.db.models.deletion
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0013_auto_20220620_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga_emprego',
            name='atribuicoes',
            field=models.TextField(blank=True, default='', verbose_name='Atribuições'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='carga_horaria',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Carga Hórario'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='salario',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='vaga_emprego',
            name='tipo_de_vaga',
            field=models.CharField(choices=[('NML', 'Padrão'), ('JAP', 'Jovem aprendiz'), ('PED', 'Pessoa com deficiência')], default='NML', max_length=3),
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do candidato')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento do candidato')),
                ('email', models.EmailField(max_length=254, verbose_name='Email p/ contato com o candidato')),
                ('celular', models.CharField(blank=True, max_length=11, null=True, validators=[vagas.validations.validate_TELEFONE], verbose_name='Celular p/ contato com o candidato')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('candidato_ativo', models.BooleanField(default=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga_emprego')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nome'],
            },
        ),
    ]
