# Generated by Django 3.2.13 on 2022-08-05 19:20

from django.db import migrations, models
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0014_auto_20220805_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome:')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[vagas.validations.validate_CPF], verbose_name='CPF:')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email:')),
                ('bairro', models.CharField(max_length=40, verbose_name='Bairro:')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('telefone', models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone:')),
            ],
        ),
    ]
